import MessageInfo from "../interfaces/messageInfo";

export const d96a_message_infos: MessageInfo[] = [
  { name: `Application error and acknowledgement`, version: `APERAK`, introduction: `The function of this message is: a)  to inform a message issuer that his message has been received by the addressee's application and has been rejected due to errors encountered during its processing in the application. b)  to acknowledge to a message issuer the receipt of his message by the addressee's application.`},
  { name: `Authorization`, version: `AUTHOR`, introduction: `An Authorization Message is sent by the Ordering Customer (or Payor or Agent on behalf of the Ordering Customer) or by a third party having authority on the Ordering Customer's payments to the Ordered Bank, to authorize the Ordered Bank to execute a given financial transaction.
This financial transaction might relate to both multiple messages like PAYMUL and DIRDEB, and single instruction messages like PAYORD and PAYEXT.
An Authorization Message could also be sent from the Ordered Bank to the Ordering Customer or its Authorization Authority to request authorization for a given financial transaction.
Throughout this document the term 'Original Message' refers to the message to be authorized.`},
  { name: `Banking status`, version: `BANSTA`, introduction: `A BANSTA message is sent by a financial institution to its customer and/or vice versa and among financial institutions. It is used for all kind of enquiries, answers and status information at application level.`},
  { name: `Bayplan/stowage plan occupied and empty locations`, version: `BAPLIE`, introduction: `A message to transmit information about equipment and goods on a means of transport, including their location on the means of transport. The message can be exchanged between (liner's) agents, tonnage centers, stevedores and ships masters/operators (see section 1.3 for more details).`},
  { name: `Bayplan/stowage plan total numbers`, version: `BAPLTE`, introduction: `A message to transmit information about the total numbers of equipment and quantity of goods on a means of transport. The message can be exchanged between (liner's) agents, tonnage centers, stevedores and ships masters/operators (see section 1.3 for more details).`},
  { name: `Bank transactions and portfolio transactions report`, version: `BOPBNK`, introduction: `The message could be sent by banks to BOP compiler for reporting of the banks' own transactions, aggregated individual customer transactions and portfolio transactions. The message could also be used for reporting the assets and liabilities positions of the banks.`},
  { name: `Balance of payment customer transaction report`, version: `BOPCUS`, introduction: `Message sent by banks to the Balance of payment (BOP) compiler for reporting - one by one - individual customer transactions (debit and credit) processed during a specific time period. Actually, this transaction information can be distilled - one by one- from PAYORD / PAYMUL / PAYEXT and BOPINF messages respectively.`},
  { name: `Direct balance of payment declaration`, version: `BOPDIR`, introduction: `The message can be sent by non-bank residents to report directly to the Balance of Payments (BOP) compiler on:
. transactions via bank accounts held at a resident bank . transactions via bank accounts held at a non-resident bank . transactions and clearing via accounts with non-bank non-residents . foreign assets and liabilities . information in the context of a BOP-related survey (stocks and flows); for those countries which base their compilation of the BOP on surveys.`},
  { name: `Balance of payment information from customer`, version: `BOPINF`, introduction: `Message sent by a payee to its bank on receipt of one specified amount as a settlement of a transaction with a non-resident. The Balance of Payment (BOP) compiler has to be informed of the transaction via the payee's bank.`},
  { name: `Call info`, version: `CALINF`, introduction: `A message from a liner agent to a stevedore providing information concerning the planned arrival of a vessel and the expected container operations.
This message is part of a total set of container-related messages. These messages serve to facilitate the intermodal handling of containers by streamlining the information exchange. The business scenario for the container messages is clarified in a separate document, called: 'Guide to the scenario of EDIFACT container messages'.`},
  { name: `Container discharge/loading report`, version: `COARRI`, introduction: `A message by which the container terminal reports that the containers specified have been discharged from a seagoing vessel (discharged as ordered, overlanded or shortlanded), or have been loaded into a seagoing vessel.
This message is part of a total set of container-related messages. These messages serve to facilitate the intermodal handling of containers by streamlining the information exchange. The business scenario for the container messages is clarified in a separate document, called: 'Guide to the scenario of EDIFACT container messages'.`},
  { name: `Container gate`, version: `CODECO`, introduction: `A message by which a terminal, depot, etc. confirms that the containers specified have been delivered or picked up by the inland carrier (road, rail or barge). This message can also be used to report internal terminal container movements (excluding loading and discharging the vessel).
This message is part of a total set of container-related messages. These messages serve to facilitate the intermodal handling of containers by streamlining the information exchange. The business scenario for the container messages is clarified in a separate document, called: 'Guide to the scenario of EDIFACT container messages'.`},
  { name: `Permit expiration/clearance ready notice`, version: `CODENO`, introduction: `Notice specifying the cargo for which either the validity of the permits/Customs documents expires at short notice or for which regulatory Customs clearance has taken place.
This message is part of a total set of container-related messages. These messages serve to facilitate the intermodal handling of containers by streamlining the information exchange. The business scenario for the container messages is clarified in a separate document, called: 'Guide to the scenario of EDIFACT container messages'.`},
  { name: `Container stock report`, version: `COEDOR`, introduction: `A message to report containers that are in stock of the sending party (i.e., a terminal, depot or container freight station).
This message is part of a total set of container-related messages. These messages serve to facilitate the intermodal handling of containers by streamlining the information exchange. The business scenario for the container messages is clarified in a separate document, called: 'Guide to the scenario of EDIFACT container messages'.`},
  { name: `Container special handling order`, version: `COHAOR`, introduction: `Order to perform a specified special handling and/or service on containers.
This message is part of a total set of container-related messages. These messages serve to facilitate the intermodal handling of containers by streamlining the information exchange. The business scenario for the container messages is clarified in a separate document, called: 'Guide to the scenario of EDIFACT container messages'.`},
  { name: `Commercial dispute`, version: `COMDIS`, introduction: `A notice of commercial dispute against one or more invoices is usually raised by the buyer to notify the seller that something was found wrong with the goods delivered or the services rendered (goods damaged, delivery incomplete, delivery late, etc.). The dispute must be resolved before the related invoice can be settled.
The message will be used to: - notify a dispute; - correspond about an existing dispute (structured information); - notify the settlement of a dispute.
The message will serve at the same time as the dispute notice and as the dispute answer.
Throughout this document, the term 'Buyer' refers to either the buyer or an Agent acting on behalf of the Buyer, and the term 'Seller' refers either to the seller or an Agent acting on behalf of the Seller.`},
  { name: `Advice on pending works`, version: `CONAPW`, introduction: `Typically, this message is to enable a contractor who intends to start works to advise public authorities and water, gas, telephone, electricity ... distributors of his intention and to request them to send back plans or information under any form concerning existing networks.`},
  { name: `Direct payment valuation`, version: `CONDPV`, introduction: `This message is the instruction by the contractor to the party responsible for payments, to pay the subcontractors for work completed.`},
  { name: `Drawing administration`, version: `CONDRA`, introduction: `The message will be used for the administration of each exchange of a set of engineering/CAD files. It will give additional information about the files; for example, their nature, a list of their contents and technical information necessary to interpret them.
The whole process of exchanging engineering or CAD (Computer Aided Design) files between different parties within one project will be supported by EDIFACT messages. The message CONDRA is one of these messages.`},
  { name: `Drawing organisation`, version: `CONDRO`, introduction: `The message CONDRO is intended to describe the general (project) organisation and structure, valid for a whole project or environment.
The whole process of exchanging engineering or CAD (Computer Aided Design) files between  different parties within one project will be supported by EDIFACT messages. The message CONDRO is one of these messages.`},
  { name: `Establishment of contract`, version: `CONEST`, introduction: `Upon completion of the tendering process, there is a requirement for the client or his representative to formally establish and issue the contractual Bill of Quantities. This documentation becomes the contractual basis for all future work and payment for the project.`},
  { name: `Invitation to tender`, version: `CONITT`, introduction: `At the pre-construction stage of a construction project, the Client will wish to appoint a contractor to execute the works. The first step in this appointment process is to issue an invitation to tender (ITT) to contractors this will require a commercial offer to be made by the contractor to the client.`},
  { name: `Payment valuation`, version: `CONPVA`, introduction: `Typically this message will be used between a contractor and the client's representative, during the process of approving the value and payment for work completed for a given period of time.`},
  { name: `Quantity valuation`, version: `CONQVA`, introduction: `Typically, this message will be used for a contractor to submit progress details to a client or his representative. The message will be used also for subsets of the project where work has been contracted out to other parties. In these cases the exchange would be between the subcontractor and the party that subcontracted the work.`},
  { name: `Response of pending works`, version: `CONRPW`, introduction: `This message is a reply to a CONAPW message and enables service providers to respond to a contractor giving details of any services and networks in the location where construction work is to be undertaken.`},
  { name: `Tender`, version: `CONTEN`, introduction: `Following the receipt of an invitation to tender (ITT) , a Main Contractor or subcontractor will submit a tender which is a commercial offer to execute the project work defined in the Bill of Quantities (BoQ) within the ITT.`},
  { name: `Work item quantity determination`, version: `CONWQD`, introduction: `Typically this message will be used between a contractor and the client's representative or other partners within the construction process, for justifying the work item quantities given in messages that describe the work items or their progress valuations.`},
  { name: `Container announcement`, version: `COPARN`, introduction: `The message contains an order to release, to make available, to accept or to call down containers or to announce the impending arrival of containers.
This message is part of a total set of container-related messages. These messages serve to facilitate the intermodal handling of containers by streamlining the information exchange. The business scenario for the container messages is clarified in a separate document, called: 'Guide to the scenario of EDIFACT container messages'.`},
  { name: `Container pre`, version: `COPINO`, introduction: `A message by which an inland carrier notifies of the delivery or pick-up of containers.
This message is part of a total set of container-related messages. These messages serve to facilitate the intermodal handling of containers by streamlining the information exchange. The business scenario for the container messages is clarified in a separate document, called: 'Guide to the scenario of EDIFACT container messages'.`},
  { name: `Container discharge/loading order`, version: `COPRAR`, introduction: `A message to order to the container terminal that the containers specified have to be discharged from a seagoing vessel or have to be loaded into a seagoing vessel.
This message is part of a total set of container-related messages. These messages serve to facilitate the intermodal handling of containers by streamlining the information exchange. The business scenario for the container messages is clarified in a separate document, called: 'Guide to the scenario of EDIFACT container messages'.`},
  { name: `Container release order`, version: `COREOR`, introduction: `Order to release containers, and giving permission for them to be picked up by or on behalf of a specified party. This message is part of a total set of container-related messages. These messages serve to facilitate the intermodal handling of containers by streamlining the information exchange. The business scenario for the container messages is clarified in a separate document, called: 'Guide to the scenario of EDIFACT container messages'.`},
  { name: `Container stuffing/stripping confirmation`, version: `COSTCO`, introduction: `Confirmation that specified goods/consignments have been stuffed into or stripped from LCL-containers. This message is part of a total set of container-related messages. These messages serve to facilitate the intermodal handling of containers by streamlining the information exchange. The business scenario for the container messages is clarified in a separate document, called: 'Guide to the scenario of EDIFACT container messages'.`},
  { name: `Container stuffing/stripping order`, version: `COSTOR`, introduction: `Order that specified goods/consignments are to be stuffed into (already or still to be delivered) or stripped from LCL-containers. This message is part of a total set of container-related messages. These messages serve to facilitate the intermodal handling of containers by streamlining the information exchange. The business scenario for the container messages is clarified in a separate document, called: 'Guide to the scenario of EDIFACT container messages'.`},
  { name: `Credit advice`, version: `CREADV`, introduction: `A Credit Advice is sent by the Account Servicing Financial Institution to the Account Owner to inform the Account Owner that its account has been or will be credited for a specified amount on the date indicated, in settlement of the referenced business transaction(s).`},
  { name: `Extended credit advice`, version: `CREEXT`, introduction: `An Extended Credit Advice is sent by the Account Servicing Financial Institution to the Account Owner to inform the Account Owner that its account has been or will be credited for a specified amount on the date indicated, in settlement of the referenced business transaction(s), and to provide to the Payee full details of the transactions to which the Extended Credit Advice relates.`},
  { name: `Multiple credit advice`, version: `CREMUL`, introduction: `A Multiple Credit Advice message is sent by an Account Servicing Financial Institution to the Account Owner or to a third party, which has agreed bilaterally in advance, that its account (s) has been or will be credited for specified amount (s) on the date (s) indicated, in settlement of the referenced business transaction (s).`},
  { name: `Customs cargo report`, version: `CUSCAR`, introduction: `This message permits the transfer of data from a carrier to a Customs administration for the purpose of meeting Customs cargo reporting requirements.`},
  { name: `Customs declaration`, version: `CUSDEC`, introduction: `This Customs Declaration Message (CUSDEC) permits the transfer of data from a declarant to a customs administration for the purpose of meeting legislative and/or operational requirements in respect of the declaration of goods for import, export or transit. The message may also be used, for example :
- to transmit data from an exporter in one country to an importer in another country; - to transmit consignment data from one customs administration to another; - to transmit data from a customs authority to other governments agencies and/or interested administrations. - to transmit data from a declarant to the appropriate data collection agency on the movement of goods between statistical territories.`},
  { name: `Customs express consignment declaration`, version: `CUSEXP`, introduction: `This message permits the transfer of express consignment data to a Customs Administration for the purpose of combining all three types of Customs reporting (conveyance report, cargo report and Customs Declaration) within a single message.`},
  { name: `Customs conveyance report`, version: `CUSREP`, introduction: `This Customs Conveyance Report Message (CUSREP) permits the transfer of data from a carrier to a Customs administration for the purpose of meeting Customs reporting requirements in respect of the means of transport on which cargo is carried.`},
  { name: `Customs response`, version: `CUSRES`, introduction: `This Customs Response Message (CUSRES) permits the transfer of data from a customs administration to the sender of customs data. It may also be used by Customs to transmit electronic customs clearance of goods.`},
  { name: `Debit advice`, version: `DEBADV`, introduction: `A Debit Advice is sent by the Account Servicing Financial Institution to the Account Owner to inform the Account Owner that its account has been or will be debited for a specified amount on the date indicated, in settlement of the referenced business transaction(s).`},
  { name: `Multiple debit advice`, version: `DEBMUL`, introduction: `A DEBMUL message is sent by an Account Servicing Financial Institution to the Account Owner or to a third party, which has agreed bilaterally in advance, that its account (s) has been or will be debited for specified amount (s) on the date (s) indicated, in settlement of the referenced business transaction (s).`},
  { name: `Delivery schedule`, version: `DELFOR`, introduction: `A message from buyer to supplier giving product requirements regarding details for short term delivery instructions and/or medium to long term product/service forecast for planning purposes according to conditions set out in a contract or order. The message can be used to authorize the commitment of labour and materials resources.`},
  { name: `Delivery just in time`, version: `DELJIT`, introduction: `A message provides the ability for a customer to convey precise delivery sequence and Just In Time schedule requirements to a supplier, and is intended to supplement the Delivery Schedule Message (DELFOR).`},
  { name: `Despatch advice`, version: `DESADV`, introduction: `A message specifying details for goods despatched or ready for despatch under agreed conditions.
The United Nations Despatch Advice Message serves both as a specification for Delivery Despatch Advice and also as a Returns Despatch Advice message. Throughout this document, the reference to 'Despatch Advice' may be interpreted as conveying the wider meaning of 'Delivery Despatch Advice/Returns Despatch Advice'.`},
  { name: `Direct debit`, version: `DIRDEB`, introduction: `Prior to the Direct Debit procedure, some agreement(s) would usually have been concluded :
- agreement between the Creditor and his Bank (mainly to specify the conditions of credit and the kind of direct debit).
- agreement between the Debtor and the Debtor's Bank (i.e. pre-authorization and condition of debit), or between the Creditor and the Debtor.
A Direct Debit is sent by the Creditor to the Creditor's Bank instructing it to claim specified amount(s) from the Debtor(s) and to credit the amount(s) to an account specified in the message, which the Creditor's Bank services for the Creditor in settlement of the referenced transaction(s).
Throughout this document the term 'Creditor' refers to either a Beneficiary or a Payee, likewise the term 'Debtor' refers to either an Ordering Customer or a Payor.
The term 'Bank' may be interpreted as any financial institution.
The term 'pre-authorization' refers to an agreement between a Creditor and a Debtor for
- either automatic debiting, as required,
- or for debiting unless rejected by the debtor in a period of time.
The agreement can also be made between the debtor and his bank, independently of the amount of the DIRDEB.`},
  { name: `Directory definition`, version: `DIRDEF`, introduction: `This Directory definition message (DIRDEF) permits the transfer of the contents of a UN/EDIFACT Directory set or parts thereof.`},
  { name: `Documentary credit advice`, version: `DOCADV`, introduction: `The Documentary Credit Advice message is used to indicate to the Beneficiary the terms and conditions of a documentary credit that has been originated by the Issuing Bank and received by the Advising Bank (or an Intermediary Advising Bank).`},
  { name: `Advice of an amendment of a documentary credit`, version: `DOCAMA`, introduction: `The Advice of an Amendment of a Documentary Credit message is originated by the Advising Bank, or Intermediary Advising Bank, and sent to the Beneficiary. It is used to inform the Beneficiary of the terms and conditions of an amendment to a documentary credit requested by the Applicant.`},
  { name: `Documentary credit amendment information`, version: `DOCAMI`, introduction: `The Documentary Credit Amendment  Information message is used to indicate the terms and conditions of an amended documentary credit from the Issuing Bank to the Applicant and/or Applicant's Bank.`},
  { name: `Request for an amendment of a documentary credit`, version: `DOCAMR`, introduction: `The Request for an Amendment of a Documentary Credit originated by the Applicant, or Applicant's Bank, and sent to the Issuing Bank. It is issued to  request the Issuing Bank to amend the terms and conditions of an issued Documentary Credit or to cancell the Documentary Credit.`},
  { name: `Documentary credit application`, version: `DOCAPP`, introduction: `A message from a party requesting the issuance of a documentary credit to the party providing such a service. In this message, the conditions under which the sender of the message requires the documentary credit to be issued are given.`},
  { name: `Response to an amendment of a documentary credit`, version: `DOCARE`, introduction: `The Response to an Amendment of a Documentary Credit originated by the Beneficiary and sent to the parties involved in the documentary credit. It is issued to advise the acceptance or non acceptance of an amendment.`},
  { name: `Documentary credit issuance information`, version: `DOCINF`, introduction: `The Documentary Credit Issuance Information message is used to indicate the terms and conditions of an issued documentary credit from the Issuing Bank to the Applicant and/or the Applicant's Bank.`},
  { name: `Financial cancellation`, version: `FINCAN`, introduction: `A Financial Cancellation Message is sent by the Ordering Customer (or Payor or Agent on behalf of the Ordering Customer)or by a third party having authority on the Ordering Customer's payments to the Ordered Bank to request cancellation of a given financial message or transaction.
Throughout this document: - The term 'Original Message' refers to the message to be cancelled (in full or part thereof); the term 'originator' refers to the sender of the original message.`},
  { name: `Financial statement of an account`, version: `FINSTA`, introduction: `This message can be used to cater for various communication functions between financial institutions and their customers. The most frequent function is to provide a statement of booked items confirming entries on a customer's account. The message type may contain several accounts (quoted in the B-level).`},
  { name: `General purpose`, version: `GENRAL`, introduction: `A message to enable the transmission of textual information.`},
  { name: `Generic statistical`, version: `GESMES`, introduction: `The compilation of statistics is a continuous chain starting with raw data collection, followed by a number of harmonization and aggregation processes leading to aggregated statistical data. Raw data collection is realized by means of surveys, sampling, direct reporting from individuals, economic operators. Harmonization and aggregation processes are very often handled by statistical bodies or authorized economic operators in case of direct reporting. A Generic Statistical Message (GESMES) is used by an organisation involved in this elaboration process to transmit a statistical data set. It permits the transmission of the following, either in the same and/or different messages: -the statistical concepts comprising the data set and their structure -if required, all related information ( code sets, labels, methodological notes, footnotes, etc.), -the statistical figures of the data set. This message could be used by producers and users of statistical information such as: National Statistical Offices, ministries, private and public administrations, private companies etc.`},
  { name: `Cargo/goods handling and movement`, version: `HANMOV`, introduction: `A message from a party to a warehouse/distribution center identifying the handling services and where required the movement of specified goods, limited to warehouses within the jurisdiction of the distribution centre.`},
  { name: `Forwarding and consolidation summary`, version: `IFCSUM`, introduction: `A message to be used for consolidation purposes from a party arranging forwarding and transport services to the party for which the transport of the consolidated cargo is destined. The message can be used to exchange information concerning the consolidated cargo between forwarders, carriers and agents enabling those parties to handle the consignments included in this consolidation. In addition it can be used for a collection of consignments originating from one shipper for forwarding and transport services.`},
  { name: `Forwarding and transport shipment charge calculation`, version: `IFTCCA`, introduction: `The function of this message is to request the calculation of the transport charges of a specific shipment and to answer to such a request.`},
  { name: `Dangerous goods notification`, version: `IFTDGN`, introduction: `The International Forwarding and Transport Dangerous Goods Notification message is a message from the party responsible to declare the dangerous goods (e.g. carrier's agent, freight forwarder) to the party acting on behalf of the local authority performing the checks on conformance with the legal requirements on the control of dangerous goods, normally Port Authority, conveying the information relating to one conveyance/voyage of a means of transport such as a vessel, train, truck or barge, on the dangerous goods being loaded, unloaded, and/or in transit.`},
  { name: `International transport freight costs and other charges`, version: `IFTFCC`, introduction: `A message specifying freight, handling and transport costs and other related charges between transport service providers and their customers.`},
  { name: `Dangerous cargo list`, version: `IFTIAG`, introduction: `The International Forwarding and Transport Dangerous Cargo List Message is a message:
- from the party acting on behalf of the carrier for the gathering of the dangerous goods information of the cargo in a certain port or place of call or loading, - to the party acting on behalf of the carrier in the next port or place of call or discharge,
conveying the information relating to one conveyance or voyage of a means of transport such as a vessel, train, truck or barge, on the dangerous goods being carried on board - irrespective of the operations that will take place in the next port of call. This message provides the basic information by which the message recipient can notify to the local authorities about the loading, unloading and transit-related operations, by means of the International forwarding and transport dangerous goods notification message (IFTDGN).`},
  { name: `Arrival notice`, version: `IFTMAN`, introduction: `A message from the party providing forwarding and/or transport services to the party such as has been indicated in the contract, giving notice and details of the arrival of the consignment.`},
  { name: `Booking confirmation`, version: `IFTMBC`, introduction: `A message from the party providing forwarding and/or transport services to the party booking those services giving the confirmation information to the booking of the consignment concerned. A confirmation might read that the booking of a consignment is accepted, pending, conditionally accepted or rejected.
The conditions under which requested services take place may be given in this message.`},
  { name: `Firm booking`, version: `IFTMBF`, introduction: `A message from a party definitely booking forwarding and/or transport services for a consignment to the party providing those services. The message will contain the conditions under which the sender of the messages requires the services to take place.`},
  { name: `Provisional booking`, version: `IFTMBP`, introduction: `A message from a party requesting space and/or giving brief details of a planned consignment for forwarding and/or transport services to the party providing those services. In this message, the conditions under which the planned transport should take place can be given.`},
  { name: `Instruction contract status`, version: `IFTMCS`, introduction: `A message from the party providing the transport/forwarding services to the party that issued the instructions for those services stating the actual details, terms and conditions (charges when applicable) of the service and of the consignment involved. In addition it can be used for the exchange of contract information between carriers mutually.`},
  { name: `Instruction`, version: `IFTMIN`, introduction: `A message from the party issuing an instruction regarding forwarding/transport services for a consignment under conditions agreed, to the party arranging the forwarding and/or transport services.`},
  { name: `Forwarding and transport rate information`, version: `IFTRIN`, introduction: `The function of this message is to request transport rate information and to answer to such a request.`},
  { name: `Forwarding and transport schedule and availability information`, version: `IFTSAI`, introduction: `The function of this message is to request transport schedule or availability information and to answer to such a request.`},
  { name: `International multimodal status report`, version: `IFTSTA`, introduction: `A message to report the transport status and/or a change in the transport status (i.e. event) between agreed parties.`},
  { name: `International multimodal status request`, version: `IFTSTQ`, introduction: `A message to request an International multimodal status report message (IFTSTA) in order to provide details relating to transport status and/or a change in the transport status between agreed parties.`},
  { name: `Insurance premium`, version: `INSPRE`, introduction: `The Insurance Premium message is used by communicating parties to notify the recipient about premiums due from a client. All information needed to produce a detailed request for payment can be sent.`},
  { name: `Invoice`, version: `INVOIC`, introduction: `A message claiming payment for goods or services supplied under conditions agreed between the seller and the buyer.
The United Nations Standard Invoice Message, with correct data qualification, serves also as the specification for Debit Note and Credit Note messages. Throughout this document, the reference to 'Invoice' may be interpreted as conveying the wider meaning of 'Invoice/Credit Note/Debit Note'.`},
  { name: `Inventory report`, version: `INVRPT`, introduction: `A message specifying information relating to held inventories. The Inventory report message is intended to be used in either direction between trading partners.`},
  { name: `Job application result`, version: `JAPRES`, introduction: `A message specifying decisions of an employer related to job applications and interviews and employment or rejections and, when necessary, reasons for the decisions or rejections. The message is transmitted from an employer or employment agency to an employment agency.`},
  { name: `Job information demand`, version: `JINFDE`, introduction: `A message sent by a governmental agency to an employer in response to a work grant request. This message asks for specific additional information (e.g. visa) for further processing of the work grant request.`},
  { name: `Job application proposal`, version: `JOBAPP`, introduction: `A message specifying detailed information of proposals for one or more job applicants from an employment agency to an employer. The detailed information is related to profession, occupation, age, education, experiences, salaries, other benefits, requested location of the job, work and contract conditions.`},
  { name: `Job order confirmation`, version: `JOBCON`, introduction: `The message intent is to confirm the receipt of information of a Job Order Message related to a vacancy or vacancies. The message is transmitted from an employment agency to an employer. The information is related to age, sex, profession, salaries, experiences, education, work and contract conditions.`},
  { name: `Job order modification`, version: `JOBMOD`, introduction: `A message specifying modifications of a previously sent Job Order Message of one or more offered jobs or vacancies in an enterprise or organization. The Job Order Modification Message is transmitted from an employer or employment agency to an employment office. The information and the changes detailed in the message are related to profession, experiences, salaries, education, work and contract conditions.`},
  { name: `Job order`, version: `JOBOFF`, introduction: `A message specifying details for one or more vacancies (occupation, salaries, experiences, work and contract conditions) for an employer to the employment agency.`},
  { name: `Person identification`, version: `MEDPID`, introduction: `The message is used to pass detailed information on persons from, for instance, health insurance agencies to local government in order to verify, add, change or delete person related data in information systems. The message may also be used to transfer person information between various application systems within one organisation (i.e hospital).
Usually detailed person related information for one or more persons is sent from one organisation to another who will acknowledge the message that is sent and proceed with changing, adding or deleting person data in their own files or use the transferred information to check their own registers and send a verification message back.`},
  { name: `Stowage instruction`, version: `MOVINS`, introduction: `A Stowage instruction message contains details of one means of transport vehicle, giving instructions regarding the loading, discharging and restowage of equipment and/or cargoes and the location on the means of transport where the operation must take place.`},
  { name: `Purchase order change request`, version: `ORDCHG`, introduction: `A message from the buyer to the seller, specifying details of the buyer's request to change a purchase order.`},
  { name: `Purchase order`, version: `ORDERS`, introduction: `A message specifying details for goods or services ordered under conditions agreed between the seller and the buyer.`},
  { name: `Purchase order response`, version: `ORDRSP`, introduction: `A message from the seller to the buyer, responding to a purchase order message or a purchase order change request message.`},
  { name: `Party information`, version: `PARTIN`, introduction: `A message to enable the transmission of basic information regarding locations and the related operational, administrative, financial, manufacturing and trading data.`},
  { name: `Passenger list`, version: `PAXLST`, introduction: `This Passenger List Message (PAXLST) permits the transfer of passenger/crew data from a Customs, Immigration or other designated authority in the country of departure to the appropriate authorities in the country of arrival of the means of transport.
Where national privacy legislation permits, and with the agreement of all parties involved, this message may also be exchanged between carriers and Customs, Immigration, Police or any designated authorities.
This transfer of data may occur upon departure from the sending agency and prior to arrival of the vessel/ flight at the receiving agency. This is to permit the designated authority at the place of destination to screen this data and take timely decisions related to the clearance of passengers and crew.
The transfer of data may also occur prior to departure, carriers may transmit passenger listings to customs and immigration for pre-arrival clearance.
Endorsement of this message by the Customs Cooperation Council does not necessarily mean endorsement by national Immigration or Police authorities, nor does it place any obligations on parties to apply the message.`},
  { name: `Payroll deductions advice`, version: `PAYDUC`, introduction: `The Payroll Deductions Advice is sent by a party (usually an employer or its representative) to a service providing organisation, to detail payments by payroll deductions, on behalf of employees, made to the service providing organisation.`},
  { name: `Extended payment order`, version: `PAYEXT`, introduction: `An Extended Payment Order is sent by the Ordering Customer (or Payor or Agent on behalf of the Ordering Customer) to the Ordered Bank, to instruct the Ordered Bank to debit an account it services for the Ordering Customer, and to arrange for the payment of a specified amount to the Beneficiary (or Payee or Agent in favour of Beneficiary) in settlement of the referenced business transaction(s), and to provide to the Payee full details of the transactions to which the Extended Payment Order relates.
Throughout this document, the term 'Ordering Customer' refers to either an Ordering Customer, or a Payor or Agent acting on behalf of the Ordering Customer; likewise the term 'Beneficiary' refers to either a Beneficiary, or a Payee or Agent acting on behalf of the Beneficiary.`},
  { name: `Multiple payment order`, version: `PAYMUL`, introduction: `A Multiple Payment order is sent by the Ordering Customer (or Payor or Agent on behalf of the Ordering Customer) to the Ordered Bank, to instruct the Ordered Bank to debit an account it services for the Ordering Customer, and to arrange for the payment of specified amounts to several Beneficiaries (or Payees) in settlement of the referenced business transaction(s).
Throughout this document, the term 'Ordering Customer' refers to either an Ordering Customer, or a Payor or Agent acting (sending) on behalf of the Ordering Customer; likewise the term 'Beneficiary' refers to either a Beneficiary, or a Payee or Agent acting on behalf of the Beneficiary.`},
  { name: `Payment order`, version: `PAYORD`, introduction: `A Payment Order is sent by the Ordering Customer (or Payor or Agent on behalf of the Ordering Customer) to the Ordered Bank, to instruct the Ordered Bank to debit an account it services for the Ordering Customer, and to arrange for the payment of a specified amount to the Beneficiary (or Payee or Agent in favour of Beneficiary) in settlement of the referenced business transaction(s). Throughout this document, the term 'Ordering Customer' refers to either an Ordering Customer, or a Payor or Agent acting on behalf of the Ordering Customer; likewise the term 'Beneficiary' refers to either a Beneficiary, or a Payee or Agent acting on behalf of the Beneficiary.`},
  { name: `Price/sales catalogue`, version: `PRICAT`, introduction: `A message to enable the transmission of information regarding pricing and catalogue details for goods and services offered by a seller to a buyer.`},
  { name: `Product exchange reconciliation`, version: `PRODEX`, introduction: `The Product Exchange Message is a communication between two trading partners with agreements for the loan of products to each other, to provide information about movements of products from and to various locations on particular dates.
The message gives additional information on the outstanding balances of each product between the trading partners.
No financial value is attached to the products and settlement is usually carried out between like products.`},
  { name: `Insurance premium payment`, version: `PRPAID`, introduction: `The Insurance Premium Payment message is used by communicating parties to notify the recipient about premiums to be collected, paid, not paid or partly paid, either individually or in series via borderaux or statements.
The exchanging partners are insurers and insurance intermediaries.`},
  { name: `Quality data`, version: `QALITY`, introduction: `A message to enable the transmission of the results of tests performed to satisfy a specified product or process requirement. The content includes, but is not limited to, test data and measurements, statistical information, and the testing methods employed.`},
  { name: `Quote`, version: `QUOTES`, introduction: `A message which provides potential sellers with the ability to provide price, delivery schedule, and other conditions for potential sales of goods or services.`},
  { name: `Raw data reporting`, version: `RDRMES`, introduction: `A Raw data reporting message (RDRMES) is sent in response to predefined and identified questions. Raw data are collected by numerous offices in the public and private sectors. Much of the data is predefined and repetitious. The data are often codified such that their description has been pre-set and meets the criteria of the collector.`},
  { name: `Receiving advice`, version: `RECADV`, introduction: `This message is to address the business needs related to the goods receipt. This message is used to report the physical receipt of goods. The message allows for the reporting of discrepancies in products, quantities, terms, packages, etc.
The message may contain only the information that the received consignment is completely in line with the consignment information given in the Despatch advice message. In case there is no detail to be provided.
The message may inform about the discrepancies: - between the received consignment and consignment information given in the Despatch advice message. - between the received goods and the ordered goods in the ORDERS, DELFOR or DELJIT information.`},
  { name: `Credit risk cover`, version: `RECECO`, introduction: `Factoring companies provide their clients (the seller) protection against the risk of credit losses on sales to the buyers. Credit protection is provided on each approved customer (buyer) of the seller.
The message will be used to apply for preliminary credit assessment (used during negotiation with prospective clients); apply for credit protection; reply to credit requests; revise amount and expiry date of credit protection and terms; cancel credit protection.
The message will serve at the same time as the request for credit risk cover and as the answer (approval or rejection to that request).`},
  { name: `Reinsurance claims`, version: `RECLAM`, introduction: `A reinsurance claims message is exchanged between insurers, professional intermediaries, reinsurers to send information concerning a loss and/or to request settlement (payment or refund) concerning the loss.`},
  { name: `Remittance advice`, version: `REMADV`, introduction: `The Remittance Advice is a communication between trading partners, e.g. seller, buyer, financial institutions, which provides a detailed accounting relative to a payment, or other form of financial settlement, for the provision of goods and/or services as detailed in the advice.`},
  { name: `Request for document`, version: `REQDOC`, introduction: `A message to enable a party request the sending, or re-sending, of data, either as a document or message, or in some other agreed form.`},
  { name: `Request for quote`, version: `REQOTE`, introduction: `A message which provides potential buyers with the ability to solicit price, delivery schedule, and other conditions from potential sellers of goods or services.`},
  { name: `Reinsurance settlement`, version: `RESETT`, introduction: `A reinsurance settlement message is exchanged by insurers, reinsurers, bureaux, brokers and professional reinsurance intermediaries to send all information that enables to identify, reconcile and set-off technical accounts.`},
  { name: `Reservation`, version: `RESMSG`, introduction: `A Reservation message is sent by a tourism operator to one or more service providers in order to request desired services. These services may be subject to confirmation by any of the parties concerned.`},
  { name: `Reinsurance technical account`, version: `RETACC`, introduction: `The RETACC is used by the sender to report to the receiver the latter's position in the sender's books with respect to one single reinsurance contract. It is in this sense a type of account for services rendered, and may initiate a payment flow either directly or via a periodical overview statement.`},
  { name: `Safety and hazard data`, version: `SAFHAZ`, introduction: `The Safety and hazard data message is to enable the communication of safety data and advice on relevant materials supplied to industrial customers so as to enable them to take measures to protect their employees and the environment from any potential harmful effects from these materials.`},
  { name: `Sanitary/phytosanitary certificate`, version: `SANCRT`, introduction: `A Sanitary/Phytosanitary Certificate permits an inspection authority to attest to the status (health, hygiene, freedom from disease or insect pests) of animal, plant or fish product, and provides basic details about the means of conveyance of that product.`},
  { name: `Sales forecast`, version: `SLSFCT`, introduction: `A message to enable the transmission of forecast data related to products or services, such as corresponding location, period, product identification, pricing, monetary amount, quantity, market sector information, sales parties. It enables the recipient to process the information automatically and use it for production, planning, marketing, statistical purposes, etc.`},
  { name: `Sales data report`, version: `SLSRPT`, introduction: `A message to enable the transmission of sales data related to products or services, such as corresponding location, period, product identification, pricing, monetary amount, quantity, market sector information, sales parties. It enables the recipient to process the information automatically and use it for production, planning, marketing, statistical purposes, etc.`},
  { name: `Modification of identity details`, version: `SSIMOD`, introduction: `The SSIMOD message is sent to communicate to the country of first registration the modification of identity details which took place since the last transmission related to the worker.`},
  { name: `Worker's insurance history`, version: `SSRECH`, introduction: `The SSRECH message is sent by a designated body in one State to the equivalent body in another State giving details of a worker's Social Security insurance history as requested by the latter State.`},
  { name: `Notification of registration of a worker`, version: `SSREGW`, introduction: `The SSREGW message is exchanged between designated bodies to enable interchange and registration of a worker's social security number. The message is also exchanged by designated bodies to request and compile details of worker's social security insurance record.`},
  { name: `Statement of account`, version: `STATAC`, introduction: `A Statement of Account is a communication from a Seller or his agent to a Buyer or his agent, providing information about the status of an account at a specific point in time. It is used as an aid to reconciliation. At the same time it may be a reminder of payment due.`},
  { name: `Superannuation contributions advice`, version: `SUPCOT`, introduction: `The Superannuation Contributions Advice is sent by a party to an organisation administering a superannuation scheme, to detail contribution payments made for members of the superannuation scheme.`},
  { name: `Superannuation maintenance`, version: `SUPMAN`, introduction: `The Superannuation Maintenance Message is sent by a party to an organisation administering a superannuation scheme, to specify membership maintenance information about superannuation scheme members.`},
  { name: `Supplier response`, version: `SUPRES`, introduction: `A Reservation message is sent by a tourism operator to one or more service providers in order to request desired services. These services may be subject to confirmation by any of the parties concerned. The Supplier response presented herein is the response to the Reservation message (RESMSG).`},
  { name: `Tank status report`, version: `TANSTA`, introduction: `A message from a vessel to the shipplanning department of a shipping line and vice versa (e.g. via satellite), giving details about the contents of ballast tanks, fuel tanks, water tanks and other figures necessary for the calculation of the stability of the vessel.`},
  { name: `Vessel departure`, version: `VESDEP`, introduction: `A message from a stevedore to a liner agent informing the latter party of the closing of a vessel's file and giving information on the actual container operations.
This message is part of a total set of container-related messages. These messages serve to facilitate the intermodal handling of containers by streamlining the information exchange. The business scenario for the container messages is clarified in a separate document, called: 'Guide to the scenario of EDIFACT container messages'.`},
  { name: `Work grant decision`, version: `WKGRDC`, introduction: `A message specifying details of decisions of the governmental agency to an employer relating to a work grant request or permit for one or more workers.`},
  { name: `Work grant request`, version: `WKGRRE`, introduction: `A message specifying details of requests to a governmental authority from an employer for workers who need a work grant or permit.`},
];
